# deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fotopie
  namespace: fotopie-dev
spec:
  selector:
    matchLabels:
      app: fotopie
      profile: fotopie
  replicas: 1
  template:
    metadata:
      labels:
        app: fotopie
        profile: fotopie
    spec:
      containers:
      - name: fotopie
        image: 206053821616.dkr.ecr.ap-southeast-2.amazonaws.com/fotopie:latest
        ports:
        - containerPort: 9090

# service file
apiVersion: v1
kind: Service
metadata:
  name: fotopie
  labels:
    app: fotopie
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: fotopie
  type: LoadBalancer
