name: Provision or Destroy Infrastructure
on:
  workflow_dispatch:
    inputs:
      infrastructure:
         description: 'Choose to provision or de-provision the AWS infrastructure'
         required: true
         default: 'provision'
         type: choice
         options:
         - provision
         - deprovision

jobs:
  provision: 
    if: ${{ inputs.infrastructure == 'provision' }} 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.FOTOPIE_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.FOTOPIE_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Terraform provision AWS resources
      run: |
         terraform init
         terraform apply -var-file backend-uat.tfvars --auto-approve
  
  de-provision:
    if: ${{ inputs.infrastructure == 'deprovision' }} 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.FOTOPIE_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.FOTOPIE_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Terraform provision AWS resources
      run: |
        terraform init
        terraform destroy --auto-approve
